# Számítógépes Problémamegoldás Jupyter Notebook (Python 3)

### Baumgartner Zoé Eszter - WWNEAK

## 4. óra [2016. 10. 03.]
### Feladat 03

#### 03 - Kétindexes array

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
B=randint(0,9,(10,10))
B

array([[8, 5, 8, 1, 7, 8, 6, 6, 8, 7],
       [6, 4, 5, 3, 0, 2, 6, 7, 4, 8],
       [1, 0, 0, 8, 5, 1, 1, 0, 7, 7],
       [0, 3, 5, 5, 6, 6, 3, 3, 5, 8],
       [0, 5, 0, 0, 2, 7, 0, 7, 1, 8],
       [1, 4, 8, 3, 1, 7, 4, 2, 8, 6],
       [7, 8, 7, 7, 2, 5, 7, 1, 6, 1],
       [2, 2, 7, 2, 0, 5, 2, 5, 5, 6],
       [6, 7, 4, 2, 6, 7, 5, 7, 8, 0],
       [4, 4, 6, 2, 4, 3, 2, 2, 5, 0]])

1. Írasd ki a B array bal alsó 5x7-es almátrixát!

In [23]:
B[5:,:7]

array([[1, 4, 8, 3, 1, 7, 4],
       [7, 8, 7, 7, 2, 5, 7],
       [2, 2, 7, 2, 0, 5, 2],
       [6, 7, 4, 2, 6, 7, 5],
       [4, 4, 6, 2, 4, 3, 2]])

2. Írass ki minden második elemet a B array második sorából!

In [39]:
B[1, 1::2]

array([4, 3, 2, 7, 8])

3. Írass ki minden háromnál nagyobb elemet a B array 7. oszlopábol!

In [55]:
B2 = B[:,6]

In [57]:
B2[B2>3]

array([6, 6, 4, 7, 5])

4. Írasd ki azokat az elemeket a B array 3. oszlopából, amelyeknek a sorában a 4. oszlopban 5-nél kisebb elem áll!

In [71]:
B3 = B[:,3] # 4. oszlop

In [76]:
B3_1 = B[:,2] # 3. oszlop

In [77]:
B3_1[B3<5]

array([8, 5, 0, 8, 7, 4, 6])